version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      npm-safe-updates:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
    commit-message:
      prefix: deps

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      actions-updates:
        patterns:
          - "*"
    commit-message:
      prefix: ci
